# Generated by Django 4.2.11 on 2024-03-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userprofile_delete_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Signup',
        ),
    ]
