# Generated by Django 4.2.11 on 2024-03-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
