# Generated by Django 4.2.11 on 2024-03-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
